#include<bits/stdc++.h>
using namespace std;
int main()
{
    ios_base::sync_with_stdio(false);
    int t,n,a[100000],b[100000],c,d=0,e,f=0,g,h,i,j,pa[100000];
    cin>>t;
    while(t--)
    {
        cin>>n;
        for(i=0;i<n;i++)
        {
            cin>>a[i];
            b[i]=a[i];
        }
        sort(b,b+n);
        c=b[0];
        for(i=0;i<n;i++)
        {
            if(a[i]==b[i])
            {
                a[i]=0;
            }
            pa[i]=a[i];
        }
        for(i=0;i<n;i++)
        {
            if(pa[i]==0)
            {
                continue;
            }
            else{
                if(pa[i]%c==0)
                {
                    pa[i]=0;
                }
            }
        }
        sort(pa,pa+n);
        for(i=0;i<n;i++)
        {
            if(pa[i]>0)
            {
                e=pa[i];
                break;
            }
        }
        for(i=0;i<n;i++)
        {
            if(pa[i]==0)
            {
                continue;
            }
            else{
                if(pa[i]%c!=0)
                {
                    d=1;
                    break;
                }
            }
        }
        if(d==1)
        {
            cout<<"NO"<<endl;
        }
        else{
            if(c==e)
            {
                cout<<"YES"<<endl;
            }
            else{
                for(i=0;i<n;i++)
                {
                    if(pa[i]==0 || pa[i]==e)
                    {
                        continue;
                    }
                    else{
                        if(pa[i]%e==0)
                        {
                            f=1;
                            break;
                        }
                    }
                }
                if(f==0)
                {
                    cout<<"YES"<<endl;
                }
                else{
                    cout<<"NO"<<endl;
                }
            }
        }
        d=0;f=0;
    }
}
